# This file configures your backend service for Choreo.
# It should be located at: backend/.choreo/component.yaml

apiVersion: v1alpha1
kind: Component
metadata:
  # The name of your component in the Choreo console.
  name: backend
spec:
  # Specifies that this component is a long-running service.
  type: Service

  build:
    # This section defines how Choreo builds your code.
    # IMPORTANT: This must match the branch you are pushing your code to.
    branch: master

  # This section defines how your service is exposed to the internet.
  inbound:
    - name: "rest-api" # A unique name for your API endpoint.
      # This is the internal port your application listens on.
      # Gunicorn and Uvicorn default to 8000, so this is correct.
      port: 8000
      # The type of the endpoint. REST is correct for a Django API.
      type: REST
      # This makes the endpoint accessible from the public internet.
      networkVisibility: Public
      # The base path for your API. A single slash (/) means it will be available
      # at the root of your service URL (e.g., https://<...>.choreoapps.dev/).
      context: /
      